package Visuals;
import Code.*;
        
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;

import java.util.Timer;
import java.util.TimerTask;


public class framePreguntas extends javax.swing.JFrame {
    public static String[][] basePreguntas = LecturaEscritura.lecturaPreguntas("Preguntas.txt",40);
    public boolean estrella;
    public Jugador jug1,jug2;
    Timer time;
    int pregunta;
    /**
     * Creates new form framePreguntas
     */
    public framePreguntas(){
        initComponents();
    }
    public framePreguntas(int x, Jugador jug1, Jugador jug2, boolean estrella) {
        initComponents();
        this.estrella = estrella;
        this.jug1 = jug1;
        this.jug2 = jug2;
        pregunta = x;
        time = new Timer();
        time.scheduleAtFixedRate(new TimerTask(){
            int i=15;
            @Override
            public void run(){
                pgbTiempo.setValue((100/15)*i);
                txtTiempoRestante.setText(""+i);
                i--;
                if(i<0){
                    mostrarmsg();
                    time.cancel();
                    new frameRuleta(jug1,jug2,false).setVisible(true);
                }
            }
        },0,1000);
        setTxts(pregunta);
    }
    private void mostrarmsg(){
        JOptionPane.showMessageDialog(this, "El tiempo se ha terminado):", "ATENCION", JOptionPane.INFORMATION_MESSAGE);
    }
    private void setTxts(int i){
        ArrayList<String> respuestas = new ArrayList<>();
        for(int cont=2;cont<6;cont++){
            respuestas.add(basePreguntas[i][cont]);
        }
        for(int cont=0;cont<4;cont++){
            Collections.shuffle(respuestas);//Aplicamos varias veces el metodo ya que shuffle suele fallar
        }
        this.txtPregunta.setText(basePreguntas[i][1]);
        this.txtRespuesta1.setText(respuestas.get(0));
        this.txtRespuesta2.setText(respuestas.get(1));
        this.txtRespuesta3.setText(respuestas.get(2));
        this.txtRespuesta4.setText(respuestas.get(3));
    }
    public void obtenerRespuesta(String respuesta, int i){
        if(respuesta.equals(basePreguntas[i][2])){
            time.cancel();
            if(jug1.enturno){
                jug1.progreso+=1;
                if(estrella){
                    jug1.estrellas++;
                }
            }else{
                jug2.progreso+=1;
                if(estrella){
                    jug2.estrellas++;
                }
            }
            
            JOptionPane.showMessageDialog(this, "Tu respuesta fue correcta", "ATENCION", JOptionPane.INFORMATION_MESSAGE);
            new frameRuleta(jug1,jug2,false).setVisible(true);
            revisarGanador();
        }else{
            time.cancel();
            if(jug1.enturno){
                jug1.enturno=false;
                jug2.enturno=true;
                if(estrella){
                    jug1.progreso-=2;
                }
            }
            else{
                jug1.enturno=true;
                jug2.enturno=false;
                if(estrella){
                    jug1.progreso-=2;
                }
            }
            
            JOptionPane.showMessageDialog(this, "Tu respuesta fue incorrecta.\n La respuesta correcta era: " + basePreguntas[i][2] , "ATENCION", JOptionPane.ERROR_MESSAGE);
            new frameRuleta(jug1,jug2,false).setVisible(true);
        }
    }
    private void revisarGanador(){
        boolean winjug1 = true,winjug2 = true;
        if(jug1.estrellas!=5){
            winjug1 = false;
        }
        if(jug2.estrellas!=5){
            winjug2 = false;
        }
        if(winjug1){
            JOptionPane.showMessageDialog(this, "Ha ganado el jugador: " + jug1.nombre, "ATENCION", JOptionPane.INFORMATION_MESSAGE);
            for (int cont=0;cont<5;cont++){
                jug1.estrellas=0;
                jug2.estrellas=0;
            }
            new frameMainpg(jug1,jug2).setVisible(true); 
        }
        if(winjug2){
            JOptionPane.showMessageDialog(this, "Ha ganado el jugador: " + jug2.nombre, "ATENCION", JOptionPane.INFORMATION_MESSAGE);
            for (int cont=0;cont<5;cont++){
                jug1.estrellas=0;
                jug2.estrellas=0;
            }
            new frameMainpg(jug1,jug2).setVisible(true); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panPregunta = new javax.swing.JPanel();
        txtPregunta = new javax.swing.JLabel();
        panRespuesta1 = new javax.swing.JPanel();
        txtRespuesta1 = new javax.swing.JLabel();
        panRespuesta2 = new javax.swing.JPanel();
        txtRespuesta2 = new javax.swing.JLabel();
        panRespuesta3 = new javax.swing.JPanel();
        txtRespuesta3 = new javax.swing.JLabel();
        panRespuesta4 = new javax.swing.JPanel();
        txtRespuesta4 = new javax.swing.JLabel();
        txtTiempoRestante = new javax.swing.JLabel();
        txtTiempoRestante1 = new javax.swing.JLabel();
        pgbTiempo = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(640, 960));

        background.setBackground(new java.awt.Color(153, 0, 204));
        background.setPreferredSize(new java.awt.Dimension(640, 960));

        panPregunta.setBackground(new java.awt.Color(102, 0, 255));

        txtPregunta.setFont(new java.awt.Font("NanumGothic", 0, 24)); // NOI18N
        txtPregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPregunta.setText("Pregunta");
        txtPregunta.setAlignmentX(0.5F);

        javax.swing.GroupLayout panPreguntaLayout = new javax.swing.GroupLayout(panPregunta);
        panPregunta.setLayout(panPreguntaLayout);
        panPreguntaLayout.setHorizontalGroup(
            panPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPreguntaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(txtPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        panPreguntaLayout.setVerticalGroup(
            panPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPreguntaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );

        panRespuesta1.setBackground(new java.awt.Color(102, 102, 255));
        panRespuesta1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panRespuesta1.setPreferredSize(new java.awt.Dimension(540, 130));
        panRespuesta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panRespuesta1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panRespuesta1MouseEntered(evt);
            }
        });

        txtRespuesta1.setFont(new java.awt.Font("NanumGothic", 0, 24)); // NOI18N
        txtRespuesta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRespuesta1.setText("Respuesta1");
        txtRespuesta1.setAlignmentX(0.5F);

        javax.swing.GroupLayout panRespuesta1Layout = new javax.swing.GroupLayout(panRespuesta1);
        panRespuesta1.setLayout(panRespuesta1Layout);
        panRespuesta1Layout.setHorizontalGroup(
            panRespuesta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRespuesta1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtRespuesta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panRespuesta1Layout.setVerticalGroup(
            panRespuesta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRespuesta1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtRespuesta1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );

        panRespuesta2.setBackground(new java.awt.Color(102, 102, 255));
        panRespuesta2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panRespuesta2.setPreferredSize(new java.awt.Dimension(540, 130));
        panRespuesta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panRespuesta2MouseClicked(evt);
            }
        });

        txtRespuesta2.setFont(new java.awt.Font("NanumGothic", 0, 24)); // NOI18N
        txtRespuesta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRespuesta2.setText("Respuesta2");
        txtRespuesta2.setAlignmentX(0.5F);

        javax.swing.GroupLayout panRespuesta2Layout = new javax.swing.GroupLayout(panRespuesta2);
        panRespuesta2.setLayout(panRespuesta2Layout);
        panRespuesta2Layout.setHorizontalGroup(
            panRespuesta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRespuesta2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtRespuesta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panRespuesta2Layout.setVerticalGroup(
            panRespuesta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRespuesta2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtRespuesta2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );

        panRespuesta3.setBackground(new java.awt.Color(102, 102, 255));
        panRespuesta3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panRespuesta3.setPreferredSize(new java.awt.Dimension(540, 130));
        panRespuesta3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panRespuesta3MouseClicked(evt);
            }
        });

        txtRespuesta3.setFont(new java.awt.Font("NanumGothic", 0, 24)); // NOI18N
        txtRespuesta3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRespuesta3.setText("Respuesta3");
        txtRespuesta3.setAlignmentX(0.5F);

        javax.swing.GroupLayout panRespuesta3Layout = new javax.swing.GroupLayout(panRespuesta3);
        panRespuesta3.setLayout(panRespuesta3Layout);
        panRespuesta3Layout.setHorizontalGroup(
            panRespuesta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRespuesta3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtRespuesta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panRespuesta3Layout.setVerticalGroup(
            panRespuesta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRespuesta3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtRespuesta3, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );

        panRespuesta4.setBackground(new java.awt.Color(102, 102, 255));
        panRespuesta4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panRespuesta4.setPreferredSize(new java.awt.Dimension(540, 130));
        panRespuesta4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panRespuesta4MouseClicked(evt);
            }
        });

        txtRespuesta4.setFont(new java.awt.Font("NanumGothic", 0, 24)); // NOI18N
        txtRespuesta4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRespuesta4.setText("Respuesta4");
        txtRespuesta4.setAlignmentX(0.5F);

        javax.swing.GroupLayout panRespuesta4Layout = new javax.swing.GroupLayout(panRespuesta4);
        panRespuesta4.setLayout(panRespuesta4Layout);
        panRespuesta4Layout.setHorizontalGroup(
            panRespuesta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRespuesta4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtRespuesta4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panRespuesta4Layout.setVerticalGroup(
            panRespuesta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRespuesta4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtRespuesta4, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtTiempoRestante.setFont(new java.awt.Font("NanumGothic", 0, 24)); // NOI18N
        txtTiempoRestante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTiempoRestante.setText("15");
        txtTiempoRestante.setAlignmentX(0.5F);

        txtTiempoRestante1.setFont(new java.awt.Font("NanumGothic", 0, 24)); // NOI18N
        txtTiempoRestante1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTiempoRestante1.setText("Tiempo Restante:");
        txtTiempoRestante1.setAlignmentX(0.5F);

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panRespuesta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panRespuesta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panRespuesta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panRespuesta4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(pgbTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(txtTiempoRestante1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTiempoRestante, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(panPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTiempoRestante1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTiempoRestante, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(pgbTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panRespuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(panRespuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(panRespuesta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(panRespuesta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panRespuesta1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panRespuesta1MouseEntered
        
    }//GEN-LAST:event_panRespuesta1MouseEntered

    private void panRespuesta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panRespuesta1MouseClicked
        obtenerRespuesta(txtRespuesta1.getText(),pregunta);
    }//GEN-LAST:event_panRespuesta1MouseClicked

    private void panRespuesta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panRespuesta2MouseClicked
        obtenerRespuesta(txtRespuesta2.getText(),pregunta);
    }//GEN-LAST:event_panRespuesta2MouseClicked

    private void panRespuesta3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panRespuesta3MouseClicked
        obtenerRespuesta(txtRespuesta3.getText(),pregunta);
    }//GEN-LAST:event_panRespuesta3MouseClicked

    private void panRespuesta4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panRespuesta4MouseClicked
        obtenerRespuesta(txtRespuesta4.getText(),pregunta);
    }//GEN-LAST:event_panRespuesta4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framePreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framePreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framePreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framePreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new framePreguntas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel panPregunta;
    private javax.swing.JPanel panRespuesta1;
    private javax.swing.JPanel panRespuesta2;
    private javax.swing.JPanel panRespuesta3;
    private javax.swing.JPanel panRespuesta4;
    private javax.swing.JProgressBar pgbTiempo;
    private javax.swing.JLabel txtPregunta;
    private javax.swing.JLabel txtRespuesta1;
    private javax.swing.JLabel txtRespuesta2;
    private javax.swing.JLabel txtRespuesta3;
    private javax.swing.JLabel txtRespuesta4;
    private javax.swing.JLabel txtTiempoRestante;
    private javax.swing.JLabel txtTiempoRestante1;
    // End of variables declaration//GEN-END:variables
}
